# -*- coding: utf-8 -*-
"""Penjualan Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KtNqKhLiWBSVkMKbYZjNd5ox96FS6vg
"""

!pip install streamlit pyngrok historical matplotlib seaborn scikit-learn openpyxl

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler
# 
# # --- SETTING PAGE STREAMLIT ---
# st.set_page_config(page_title="Dashboard Clustering Penjualan", layout="wide")
# 
# st.title("📊 Analisis Clustering Penjualan Produk (Jan–Mar)")
# st.markdown("Aplikasi ini mengelompokkan produk berdasarkan performa penjualan menggunakan algoritma **K-Means**.")
# 
# # --- FUNGSI LOAD DATA (Sesuai dengan logic KP_YUK.ipynb) ---
# def baca_xlsx(file, bulan):
#     df = pd.read_excel(file, dtype=str)
#     df['Bulan'] = bulan
# 
#     df['Qty_numeric_temp'] = pd.to_numeric(df['Qty'], errors='coerce')
#     df['HargaSatuan_numeric_temp'] = pd.to_numeric(df['Harga Satuan'], errors='coerce')
# 
#     category_mask = df['Qty_numeric_temp'].isna() & df['HargaSatuan_numeric_temp'].isna() & df['SKU'].notna()
#     df['Kategori'] = np.nan
#     df.loc[category_mask, 'Kategori'] = df.loc[category_mask, 'SKU']
#     df['Kategori'] = df['Kategori'].ffill()
# 
#     df = df[df['SKU'].astype(str).str.match(r'^\d', na=False)].copy()
#     df.drop(columns=['Qty_numeric_temp', 'HargaSatuan_numeric_temp'], inplace=True, errors='ignore')
#     return df
# 
# # --- SIDEBAR: UPLOAD 3 FILE BULANAN ---
# st.sidebar.header("📁 Upload Data Penjualan")
# file_jan = st.sidebar.file_uploader("Upload Ringkasan Penjualan - Januari (.xlsx)", type=["xlsx"])
# file_feb = st.sidebar.file_uploader("Upload Ringkasan Penjualan - Februari (.xlsx)", type=["xlsx"])
# file_mar = st.sidebar.file_uploader("Upload Ringkasan Penjualan - Maret (.xlsx)", type=["xlsx"])
# 
# if file_jan and file_feb and file_mar:
#     # Proses membaca data
#     df_jan = baca_xlsx(file_jan, 'Januari')
#     df_feb = baca_xlsx(file_feb, 'Februari')
#     df_mar = baca_xlsx(file_mar, 'Maret')
# 
#     # Penggabungan data mentah
#     df_raw = pd.concat([df_jan, df_feb, df_mar], ignore_index=True)
# 
#     # --- DATA CLEANING (Sesuai KP_YUK.ipynb) ---
#     df = df_raw.copy()
#     kolom_numerik = ['Qty', 'Harga Satuan', 'Diskon', 'Harga Jual Setelah Diskon', 'Cogs', 'Gross Profit']
#     for kol in kolom_numerik:
#         if kol in df.columns:
#             df[kol] = pd.to_numeric(df[kol], errors='coerce')
# 
#     df = df.dropna(subset=['Produk', 'Qty', 'Harga Satuan'])
#     df = df[(df['Qty'] > 0) & (df['Harga Satuan'] > 0)]
#     df['Harga_Unit'] = (df['Harga Satuan'] / df['Qty']).round(0)
#     df['Diskon'] = df['Diskon'].fillna(0)
#     df['Gross Profit'] = df['Gross Profit'].fillna(0)
# 
#     # Filter Produk Eksklusif / Musiman
#     EXCL_KATEGORI = ['SPECIAL RAMADHAN', "VALENTINE'S SPECIAL PACKAGE", 'VALENTINE PACKAGE', 'Paket Event', 'FREE [Deleted]', 'Special Bundling [Deleted]']
#     EXCL_PRODUK = ['Mineral', 'Ice Cube', 'Nasi Putih']
# 
#     mask_eksklusif = df['Kategori'].isin(EXCL_KATEGORI) | df['Produk'].isin(EXCL_PRODUK)
#     df_filtered = df[~mask_eksklusif].copy()
# 
#     # --- INTERFACE UTAMA DASHBOARD ---
#     tab1, tab2, tab3 = st.tabs(["📋 Ringkasan Data", "⚙️ Clustering K-Means", "🔍 Detail Cluster"])
# 
#     with tab1:
#         st.subheader("Eksplorasi Data Setelah Cleaning")
#         col1, col2, col3 = st.columns(3)
#         col1.metric("Total Baris Produk", len(df_filtered))
#         col2.metric("Total Qty Terjual", int(df_filtered['Qty'].sum()))
#         col3.metric("Total Gross Profit", f"Rp {df_filtered['Gross Profit'].sum():,.0f}")
# 
#         st.markdown("### Sampel Data Analisis:")
#         st.dataframe(df_filtered[['SKU', 'Produk', 'Kategori', 'Qty', 'Harga Satuan', 'Gross Profit', 'Bulan']].head(10))
# 
#     with tab2:
#         st.subheader("Konfigurasi Model K-Means")
# 
#         # Pilihan fitur untuk clustering
#         fitur_pilihan = st.multiselect("Pilih Fitur untuk Clustering:", ['Qty', 'Harga Satuan', 'Gross Profit', 'Harga_Unit'], default=['Qty', 'Gross Profit'])
# 
#         # Jumlah cluster dinamis
#         n_clusters = st.slider("Tentukan Jumlah Cluster (k):", min_value=2, max_value=6, value=3)
# 
#         if len(fitur_pilihan) >= 2:
#             # Mengelompokkan data per produk untuk clustering yang stabil
#             df_cluster_base = df_filtered.groupby(['SKU', 'Produk', 'Kategori'])[fitur_pilihan].sum().reset_index()
# 
#             # Standardisasi Fitur
#             scaler = StandardScaler()
#             X_scaled = scaler.fit_transform(df_cluster_base[fitur_pilihan])
# 
#             # Pemodelan K-Means
#             kmeans = KMeans(n_clusters=n_clusters, random_value=42, n_init=10)
#             df_cluster_base['Cluster'] = kmeans.fit_predict(X_scaled)
# 
#             st.success(f"✅ Berhasil memodelkan {n_clusters} cluster.")
# 
#             # --- VISUALISASI SCATTER PLOT ---
#             st.markdown("### Visualisasi Cluster")
#             fig, ax = plt.subplots(figsize=(8, 5))
#             sns.scatterplot(
#                 data=df_cluster_base,
#                 x=fitur_pilihan[0],
#                 y=fitur_pilihan[1],
#                 hue='Cluster',
#                 palette='Set1',
#                 s=100,
#                 ax=ax
#             )
#             ax.set_title(f"Clustering Berdasarkan {fitur_pilihan[0]} dan {fitur_pilihan[1]}")
#             st.pyplot(fig)
# 
#             # Tampilkan rata-rata karakteristik per cluster
#             st.markdown("### Karakteristik Rata-rata Tiap Cluster:")
#             df_profile = df_cluster_base.groupby('Cluster')[fitur_pilihan].mean()
#             st.dataframe(df_profile.style.format("{:,.2f}"))
#         else:
#             st.warning("⚠️ Mohon pilih minimal 2 fitur untuk visualisasi scatter plot.")
# 
#     with tab3:
#         st.subheader("Cari Informasi Anggota Cluster")
#         if 'df_cluster_base' in locals():
#             pilih_c = st.selectbox("Pilih nomor cluster yang ingin dilihat:", sorted(df_cluster_base['Cluster'].unique()))
#             df_anggota = df_cluster_base[df_cluster_base['Cluster'] == pilih_c]
# 
#             st.write(f"Menampilkan **{len(df_anggota)}** produk yang masuk ke dalam **Cluster {pilih_c}**:")
#             st.dataframe(df_anggota[['SKU', 'Produk', 'Kategori'] + fitur_pilihan])
# 
# else:
#     st.info("💡 Silakan upload ketiga file Excel bulanan (Januari, Februari, Maret) di sidebar untuk memulai analisis!")